#配置数据源
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=store;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456

#配置MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wfit






















